### PR TITLE
Code base

### PR DESCRIPTION
**Pull request by Scrip00**
Mmm fancy code

### CODE REVIEW

**Comment by pabloooooo** [comment]
Their is no authentication in this code, doesnt return a auth token back to user. Also generates random 6 digit codes that arent stored anywhere so we cant even check if they are valid

**Comment by Scrip00** [comment]
Wdym no authentication? Codes are send back to front-end to check the validity

**Comment by Scrip00** [comment]
Codes are not supposed to be stored, they are temporary. Take a better look huh

**Comment by figamin** [comment]
code is decent but frontend should be the one to approve

**Review by KassidyKhang — APPROVED** [review]
Nice!

**Pull request merged**
